// <auto-generated />
using System;
using CodeNight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeNight.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260216223120_UpdateEnumsAndSchema")]
    partial class UpdateEnumsAndSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeNight.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArtistName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("artist_name");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("genre");

                    b.HasKey("ArtistId");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Badge", b =>
                {
                    b.Property<Guid>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("badge_name");

                    b.Property<long>("Condition")
                        .HasColumnType("bigint")
                        .HasColumnName("condition");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("level");

                    b.HasKey("BadgeId");

                    b.ToTable("badges", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.BadgeAward", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("awarded_at");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("badge_awards", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Challenge", b =>
                {
                    b.Property<Guid>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChallengeName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("challenge_name");

                    b.Property<string>("ChallengeType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("challenge_type");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("condition");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<long>("RewardPoints")
                        .HasColumnType("bigint")
                        .HasColumnName("reward_points");

                    b.HasKey("ChallengeId");

                    b.ToTable("challenges", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.ChallengeAward", b =>
                {
                    b.Property<Guid>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("award_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date")
                        .HasColumnName("as_of_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id");

                    b.Property<long>("RewardPoints")
                        .HasColumnType("bigint")
                        .HasColumnName("reward_points");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AwardId");

                    b.HasIndex("DecisionId");

                    b.HasIndex("UserId", "AsOfDate")
                        .IsUnique()
                        .HasDatabaseName("ix_challenge_awards_user_id_as_of_date");

                    b.ToTable("challenge_awards", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.ChallengeDecision", b =>
                {
                    b.Property<Guid>("DecisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("decision_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("reason");

                    b.HasKey("DecisionId");

                    b.ToTable("challenge_decisions", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long>("ListenMinutes")
                        .HasColumnType("bigint")
                        .HasColumnName("listen_minutes");

                    b.Property<long>("PlaylistAdditions")
                        .HasColumnType("bigint")
                        .HasColumnName("playlist_additions");

                    b.Property<long>("Shares")
                        .HasColumnType("bigint")
                        .HasColumnName("shares");

                    b.Property<string>("TopGenre")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("top_genre");

                    b.Property<long>("UniqueTracks")
                        .HasColumnType("bigint")
                        .HasColumnName("unique_tracks");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("EventId");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_events_user_id_date");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("message");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "SentAt")
                        .HasDatabaseName("ix_notifications_user_id_sent_at");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.PointsLedgerEntry", b =>
                {
                    b.Property<Guid>("LedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ledger_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("PointsDelta")
                        .HasColumnType("bigint")
                        .HasColumnName("points_delta");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("source");

                    b.Property<Guid>("SourceRef")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ref");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LedgerId");

                    b.HasIndex("Source", "SourceRef")
                        .IsUnique()
                        .HasDatabaseName("ix_points_ledger_source_source_ref");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_points_ledger_user_id_created_at");

                    b.ToTable("points_ledger", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("track_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<long>("DurationSec")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_sec");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("track_name");

                    b.HasKey("TrackId");

                    b.HasIndex("ArtistId");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.TriggeredChallenge", b =>
                {
                    b.Property<Guid>("AwardId")
                        .HasColumnType("uuid")
                        .HasColumnName("award_id");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uuid")
                        .HasColumnName("challenge_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.HasKey("AwardId", "ChallengeId");

                    b.HasIndex("ChallengeId")
                        .HasDatabaseName("ix_triggered_challenges_challenge_id");

                    b.ToTable("triggered_challenges", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("surname");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.UserState", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("ListenMinutes7d")
                        .HasColumnType("bigint")
                        .HasColumnName("listen_minutes_7d");

                    b.Property<long>("ListenMinutesToday")
                        .HasColumnType("bigint")
                        .HasColumnName("listen_minutes_today");

                    b.Property<long>("ListenStreakDays")
                        .HasColumnType("bigint")
                        .HasColumnName("listen_streak_days");

                    b.Property<long>("PlaylistAdditionsToday")
                        .HasColumnType("bigint")
                        .HasColumnName("playlist_additions_today");

                    b.Property<long>("Shares7d")
                        .HasColumnType("bigint")
                        .HasColumnName("shares_7d");

                    b.Property<long>("SharesToday")
                        .HasColumnType("bigint")
                        .HasColumnName("shares_today");

                    b.Property<long>("TotalPoints")
                        .HasColumnType("bigint")
                        .HasColumnName("total_points");

                    b.Property<long>("UniqueTracks7d")
                        .HasColumnType("bigint")
                        .HasColumnName("unique_tracks_7d");

                    b.Property<long>("UniqueTracksToday")
                        .HasColumnType("bigint")
                        .HasColumnName("unique_tracks_today");

                    b.HasKey("UserId");

                    b.ToTable("user_states", (string)null);
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.BadgeAward", b =>
                {
                    b.HasOne("CodeNight.Domain.Entities.Badge", "Badge")
                        .WithMany("BadgeAwards")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeNight.Domain.Entities.User", "User")
                        .WithMany("BadgeAwards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.ChallengeAward", b =>
                {
                    b.HasOne("CodeNight.Domain.Entities.ChallengeDecision", "ChallengeDecision")
                        .WithMany("ChallengeAwards")
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeNight.Domain.Entities.User", "User")
                        .WithMany("ChallengeAwards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallengeDecision");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Event", b =>
                {
                    b.HasOne("CodeNight.Domain.Entities.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Notification", b =>
                {
                    b.HasOne("CodeNight.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.PointsLedgerEntry", b =>
                {
                    b.HasOne("CodeNight.Domain.Entities.User", "User")
                        .WithMany("PointsLedgerEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Track", b =>
                {
                    b.HasOne("CodeNight.Domain.Entities.Artist", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.TriggeredChallenge", b =>
                {
                    b.HasOne("CodeNight.Domain.Entities.ChallengeAward", "ChallengeAward")
                        .WithMany("TriggeredChallenges")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeNight.Domain.Entities.Challenge", "Challenge")
                        .WithMany("TriggeredChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("ChallengeAward");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.UserState", b =>
                {
                    b.HasOne("CodeNight.Domain.Entities.User", "User")
                        .WithOne("UserState")
                        .HasForeignKey("CodeNight.Domain.Entities.UserState", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Artist", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Badge", b =>
                {
                    b.Navigation("BadgeAwards");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.Challenge", b =>
                {
                    b.Navigation("TriggeredChallenges");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.ChallengeAward", b =>
                {
                    b.Navigation("TriggeredChallenges");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.ChallengeDecision", b =>
                {
                    b.Navigation("ChallengeAwards");
                });

            modelBuilder.Entity("CodeNight.Domain.Entities.User", b =>
                {
                    b.Navigation("BadgeAwards");

                    b.Navigation("ChallengeAwards");

                    b.Navigation("Events");

                    b.Navigation("Notifications");

                    b.Navigation("PointsLedgerEntries");

                    b.Navigation("UserState");
                });
#pragma warning restore 612, 618
        }
    }
}
